### ISSUE TITLE
inference of Ks value from paranome 

### ISSUE THREAD

**Issue by manoharbisht1998** [heche-psb/wgd#15]
Hi 
I have run the whole paranome ks distribution and i received the plot through "viz"  parameter with elmm mixture model. But i am confused with different values associated with different lognormal optimization, as what would be the final Ks value from the plot. Kindly help. 

PFA 
[Ks_inference.pdf](https://github.com/heche-psb/wgd/files/12845006/Ks_inference.pdf)

**Comment by heche-psb** [comment]
Hi, for the ELMM analysis, it's better to rerun it multiply times until you get stable results because of the random initiation of parameters . It's suggested to compare the whole paranome Ks distribution to the anchor Ks distribution (and its associated GMM results) to reach some conclusions.
