### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ZhaoHang-bio** [heche-psb/wgd#16]
Hi,

I am currently testing the wgd v2 software with the following command:

`wgd dmd sample.longestcds.fa -o 01.step-dmd -n 10
`
However, I encountered an error message:

```
12:31:22 INFO     This is wgd v2.0.23                                                                                         cli.py:32     
Segmentation fault (core dumped)
```

Could you please advise on how to resolve this issue?

**Comment by heche-psb** [comment]
Hi, it seems to be a memory issue. Can you increase the memory to 5G or 10G and try again?

**Comment by ZhaoHang-bio** [comment]
I attempted to run test data using the wgd v2.0.23 software on a compute node with 6T of memory.

`wgd dmd egu1000.fasta`

 However, the process still ended unexpectedly with a same error :
```
11:35:23 INFO     This is wgd v2.0.23 cli.py:32 
Segmentation fault (core dumped)
```

**Comment by heche-psb** [comment]
The "Segmentation fault (core dumped)" is showing that the program has problems accessing the memory. Do you "qsub" the job with enough memory required or just run the command locally on the cluster/HPC? The latter will be restricted on certain HPC.
