### ISSUE TITLE
A tutorial to customization of plots in Python?

### ISSUE THREAD

**Issue by taprs** [heche-psb/wgd#18]
Hi Hengchi!

While getting to use the pipeline more, I noticed that I am often tempted to tweak many aspects of the plots output at every stage. To name a few examples:

 - Change X axis limits in Ks distribution plots (there are options for that in `wgd ksd` and `wgd viz` but they do not seem to work)
 - Modify the order of chromosomes in the synteny dotplots, change the range of Ks values to be colored
 - Simply change the device size, e.g. to achieve 1:1 aspect ratio for self-synteny dotplots
 
I think it might be an overkill to have all of the plotting options as the `wgd` command arguments, but is it maybe not so difficult to recreate the plots with some self-tinkered options using Python? So far I had to reinvent some of the wheels myself.

Maybe it would be sufficient (and actually very cool) to have some of the simple tweaks of the main plot types (any of those mentioned above would work I guess) in a tutorial that would show how to use the Python functions of the pipeline given the pre-generated results.

Cheers,
Nikita

**Comment by heche-psb** [comment]
Thanks for the suggestions! I will make the plotting function more complete and versatile.
