### ISSUE TITLE
wgd-1.1.1/wgd/codeml.py:131: SettingWithCopyWarning:

### ISSUE THREAD

**Issue by abcbot123** [heche-psb/wgd#19]
Hi,
I got this error, when I use this code python3 wgd-1.1.1/wgd_cli.py ksd wgd_dmd/newCDS.fa.mcl newCDS.fa
How can I fix this,

/var/lib/condor/execute/slot1/dir_38140/wgd-1.1.1/wgd/codeml.py:131: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  results_dict['Ks'][gene_2][gene_1] = ks_value
/var/lib/condor/execute/slot1/dir_38140/wgd-1.1.1/wgd/codeml.py:133: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  results_dict['Ka'][gene_2][gene_1] = ka_value
/var/lib/condor/execute/slot1/dir_38140/wgd-1.1.1/wgd/codeml.py:135: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  results_dict['Omega'][gene_2][gene_1] = w
/var/lib/condor/execute/slot1/dir_38140/wgd-1.1.1/wgd/codeml.py:130: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  results_dict['Ks'][gene_1][gene_2] = ks_value
/var/lib/condor/execute/slot1/dir_38140/wgd-1.1.1/wgd/codeml.py:132: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  results_dict['Ka'][gene_1][gene_2] = ka_value
/var/lib/condor/execute/slot1/dir_38140/wgd-1.1.1/wgd/codeml.py:134: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  results_dict['Omega'][gene_1][gene_2] = w
2024-01-05 16:26:57: INFO	Performing analysis on gene family GF_000021
/var/lib/condor/execute/slot1/dir_38140/wgd-1.1.1/wgd/codeml.py:131: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  results_dict['Ks'][gene_2][gene_1] = ks_value
/var/lib/condor/execute/slot1/dir_38140/wgd-1.1.1/wgd/codeml.py:133: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  results_dict['Ka'][gene_2][gene_1] = ka_value
/var/lib/condor/execute/slot1/dir_38140/wgd-1.1.1/wgd/codeml.py:135: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  results_dict['Omega'][gene_2][gene_1] = w
/var/lib/condor/execute/slot1/dir_38140/wgd-1.1.1/wgd/codeml.py:130: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  results_dict['Ks'][gene_1][gene_2] = ks_value
/var/lib/condor/execute/slot1/dir_38140/wgd-1.1.1/wgd/codeml.py:132: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  results_dict['Ka'][gene_1][gene_2] = ka_value
/var/lib/condor/execute/slot1/dir_38140/wgd-1.1.1/wgd/codeml.py:134: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  results_dict['Omega'][gene_1][gene_2] = w
2024-01-05 16:28:06: INFO	Performing analysis on gene family GF_000022multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/joblib/_parallel_backends.py", line 350, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 131, in <listcomp>
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/var/lib/condor/execute/slot1/dir_38140/wgd-1.1.1/wgd/ks_distribution.py", line 307, in analyse_family
    out = _calculate_weighted_ks(
  File "/var/lib/condor/execute/slot1/dir_38140/wgd-1.1.1/wgd/ks_distribution.py", line 197, in _calculate_weighted_ks
    if pairwise_estimates['Ks'].iloc[i, j] > 5:
TypeError: '>' not supported between instances of 'str' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.8/dist-packages/joblib/_parallel_backends.py", line 359, in __call__
    raise TransportableException(text, e_type)
joblib.my_exceptions.TransportableException: TransportableException
___________________________________________________________________________
TypeError                                          Fri Jan  5 16:31:01 2024
PID: 4726                                   Python 3.8.10: /usr/bin/python3
...........................................................................
/usr/local/lib/python3.8/dist-packages/joblib/parallel.py in __call__(self=<joblib.parallel.BatchedCalls object>)
    126     def __init__(self, iterator_slice):
    127         self.items = list(iterator_slice)
    128         self._size = len(self.items)
    129 
    130     def __call__(self):
--> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
        self.items = [(<function analyse_family>, ('GF_000007', {'ptg000001l.2310': 'MSPLSTLLLIISLALISTFVAADPDSLQDICVADYTTGIKVNGYPCKE...AFNSQLPGTQSLATTLFGASPQVPDNVLTKAFKIGTKEVDKIKSRFVAK', 'ptg000001l.2311': 'MASIATLLLLSFALFSTSIFADPDSLQDICVADLTSGTKLNGFPCKAN...AFNSQLPGTQSLGTTLFAATPQVPDNVLSKAFKISTKEVEIIKYKFAAK', 'ptg000001l.2312': 'MASLATLVLISFALFSTSFATDPDSLQDICVADLSGVKLNGFPCKETA...SAFNSQLPGTQSIATTLFGASPEVPDNVLAKAFKIDTKTVDQIKSSFAA', 'ptg000001l.2313': 'MASFATILLLSFALFSTSFATDADSLQDICVADLASGVKLNGYPCKET...AFNSQLPGTQSIATTLFGASPQVPSNVLSKAFKISQAEVDIIKFKFLVK', 'ptg000003l.1107': 'MIFPIFIFSLLLSSSYALTQDFCVGDLSLPDAPCGFPCKKVAKVNEND...VSFSSHNPGLQILDFALFANDLPSELVEKTTFLDDVQVKKLKKVLGGTG', 'ptg000003l.1379': 'MGSFYNLLASFFLLAFAFSPLANASCNGPLQDFCVAIDEPNNASYVNG...GFNHEFPGISRHGNSLFDAKPSINYKILMRGLKLDKATEELAEGIPSGA', 'ptg000003l.1695': 'MEKRNNSNPAANATCDPGPMQDFCVGINRTYKGAFVNGEFCKNPKEVT...QNPGLLLIPNSVFQTYPPINTSILARTYKIPVKLAMRIQRSFQAEPYKG', 'ptg000003l.1887': 'MESKALACLLIFAAIYNAFAYDPDSLQDLCVANTSSSIKVNGFVCKAE...NGQLPGTQSIALTLFTATPEVPDNVLTKAFQIGTKEVDKIKSKLAPKKT', 'ptg000003l.2099': 'MASTFLKYTILSIIVAILTSRMIQASDPNILSDFLPQNTTSPDASFFT...SCFGSANAGTVSVPTTVFGTGIDAGILAKAFKTDLSTIQKIKAGLAAKA', 'ptg000003l.2462': 'MYSFSRPLALDPSYPLTFQLLFHHPPVNVFLLTPSSSSSSSSSKFSNY...NSQLPGTQSIGLSLFAATPEVPDNVLSRAFQMGTKQIDKLKTKFAPKKT', ...}, {'ptg000001l.100': 'ATGGTGTCTAGCATCGATGAAAACGAAGTTTACGCTGACTTCGCTAGA...CGTAGATTCACATTCTTGCAAGATGTATATTTTGAAGCCAATTTCTTGA', 'ptg000001l.1000': 'ATGATTGGTCCCTCTTTACAAGCTCTTGTGAAGCAACAACATGGTGTC...ATTAAGAAAAGCGCCAGCTCATAGTTTAGTCGAAGTCAGAACTTCGTGA', 'ptg000001l.1001': 'ATGCGGCTTCAGTTGTCGCCTAGTATGAGAAGCATAACGATATCGAGC...GTCGAAGCACAAAAGAGGAAGGCCGGGGCAGCTCTTCTCTAAAGGCTAG', 'ptg000001l.1002': 'ATGGCAGGCGTTCAAGACCAGTTAGAGATTAAGTTTAGGTTGACTGAC...TCCTTTGGAAAAAGGTACAAACTTTTATCTGATCATTCACATTGAATAA', 'ptg000001l.1003': 'ATGGCGACATCATCGTTTAGTGGCCTGAATTCTCCTCTATACCATTCT...AGGTGCCTTGGATGAAAAAAACAAGGGGGCCTTTTCAGGGGCCGTGTAA', 'ptg000001l.1004': 'ATGGCTGCAAATACTTTTATGTCGTATGCTGTGGATAATAAATCTGAT...TGGATTAAACTTTGATGCAGAAGAAGAAGGCTCTAATCAAAATACATGA', 'ptg000001l.1005': 'ATGGCTGAGGACGGTATTGGTTTGCCAGCGGCTTCAGAAAAAAATAAG...AACAGTTATCTCCCTCCAAGAAAAAAGGCATCCTTCCGTGAACACTTGA', 'ptg000001l.1006': 'ATGGTGGCAACCATTGCTGTGTCTTGTTCGGAATTCATAAATTTTCAA...AGTTTCGGTTGGAGCCGTGAAAAAGACGGTCTCAAGCAAGAAACGGTAG', 'ptg000001l.1007': 'ATGTGGAATTTTGCATCTAATTGCATAGCTGGAAATATTGGATCAAAA...TTTTGCATATCCTAGTTTGGATTGGCTTGTCCGAGAAATCGTCCCTTAG', 'ptg000001l.1008': 'ATGTTTCCTATTTTACTCTTCCTCCTCACAGTTACTATTTCCACCACC...AAGGCTGCAAGTTGGGGCCTCGGATGATGAAAGTTCATCTTCATCCTAG', ...}, '/var/lib/condor/execute/slot1/dir_38140/ks_tmp.3c8e141cb9cee6', 'codeml', False, 1, 100, 'fasttree', 'mafft', '/var/lib/condor/execute/slot1/dir_38140/wgd_ksd'), {})]
    132 
    133     def __len__(self):
    134         return self._size
    135 

...........................................................................
/usr/local/lib/python3.8/dist-packages/joblib/parallel.py in <listcomp>(.0=<list_iterator object>)TypeError: '>' not supported between instances of 'str' and 'int'
___________________________________________________________________________

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "wgd-1.1.1/wgd_cli.py", line 1447, in <module>
    cli()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "wgd-1.1.1/wgd_cli.py", line 625, in ksd
    ksd_(
  File "wgd-1.1.1/wgd_cli.py", line 763, in ksd_
    results = ks_analysis_paranome(
  File "/var/lib/condor/execute/slot1/dir_38140/wgd-1.1.1/wgd/ks_distribution.py", line 641, in ks_analysis_paranome
    Parallel(n_jobs=n_threads)(delayed(analysis_function)(
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 789, in __call__
    self.retrieve()
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 740, in retrieve
    raise exception
joblib.my_exceptions.JoblibTypeError: JoblibTypeError/var/lib/condor/execute/slot1/dir_38140/wgd-1.1.1/wgd/ks_distribution.py in analyse_family(family_id='GF_000007', family={'ptg000001l.2310': 'MSPLSTLLLIISLALISTFVAADPDSLQDICVADYTTGIKVNGYPCKE...AFNSQLPGTQSLATTLFGASPQVPDNVLTKAFKIGTKEVDKIKSRFVAK', 'ptg000001l.2311': 'MASIATLLLLSFALFSTSIFADPDSLQDICVADLTSGTKLNGFPCKAN...AFNSQLPGTQSLGTTLFAATPQVPDNVLSKAFKISTKEVEIIKYKFAAK', 'ptg000001l.2312': 'MASLATLVLISFALFSTSFATDPDSLQDICVADLSGVKLNGFPCKETA...SAFNSQLPGTQSIATTLFGASPEVPDNVLAKAFKIDTKTVDQIKSSFAA', 'ptg000001l.2313': 'MASFATILLLSFALFSTSFATDADSLQDICVADLASGVKLNGYPCKET...AFNSQLPGTQSIATTLFGASPQVPSNVLSKAFKISQAEVDIIKFKFLVK', 'ptg000003l.1107': 'MIFPIFIFSLLLSSSYALTQDFCVGDLSLPDAPCGFPCKKVAKVNEND...VSFSSHNPGLQILDFALFANDLPSELVEKTTFLDDVQVKKLKKVLGGTG', 'ptg000003l.1379': 'MGSFYNLLASFFLLAFAFSPLANASCNGPLQDFCVAIDEPNNASYVNG...GFNHEFPGISRHGNSLFDAKPSINYKILMRGLKLDKATEELAEGIPSGA', 'ptg000003l.1695': 'MEKRNNSNPAANATCDPGPMQDFCVGINRTYKGAFVNGEFCKNPKEVT...QNPGLLLIPNSVFQTYPPINTSILARTYKIPVKLAMRIQRSFQAEPYKG', 'ptg000003l.1887': 'MESKALACLLIFAAIYNAFAYDPDSLQDLCVANTSSSIKVNGFVCKAE...NGQLPGTQSIALTLFTATPEVPDNVLTKAFQIGTKEVDKIKSKLAPKKT', 'ptg000003l.2099': 'MASTFLKYTILSIIVAILTSRMIQASDPNILSDFLPQNTTSPDASFFT...SCFGSANAGTVSVPTTVFGTGIDAGILAKAFKTDLSTIQKIKAGLAAKA', 'ptg000003l.2462': 'MYSFSRPLALDPSYPLTFQLLFHHPPVNVFLLTPSSSSSSSSSKFSNY...NSQLPGTQSIGLSLFAATPEVPDNVLSRAFQMGTKQIDKLKTKFAPKKT', ...}, nucleotide={'ptg000001l.100': 'ATGGTGTCTAGCATCGATGAAAACGAAGTTTACGCTGACTTCGCTAGA...CGTAGATTCACATTCTTGCAAGATGTATATTTTGAAGCCAATTTCTTGA', 'ptg000001l.1000': 'ATGATTGGTCCCTCTTTACAAGCTCTTGTGAAGCAACAACATGGTGTC...ATTAAGAAAAGCGCCAGCTCATAGTTTAGTCGAAGTCAGAACTTCGTGA', 'ptg000001l.1001': 'ATGCGGCTTCAGTTGTCGCCTAGTATGAGAAGCATAACGATATCGAGC...GTCGAAGCACAAAAGAGGAAGGCCGGGGCAGCTCTTCTCTAAAGGCTAG', 'ptg000001l.1002': 'ATGGCAGGCGTTCAAGACCAGTTAGAGATTAAGTTTAGGTTGACTGAC...TCCTTTGGAAAAAGGTACAAACTTTTATCTGATCATTCACATTGAATAA', 'ptg000001l.1003': 'ATGGCGACATCATCGTTTAGTGGCCTGAATTCTCCTCTATACCATTCT...AGGTGCCTTGGATGAAAAAAACAAGGGGGCCTTTTCAGGGGCCGTGTAA', 'ptg000001l.1004': 'ATGGCTGCAAATACTTTTATGTCGTATGCTGTGGATAATAAATCTGAT...TGGATTAAACTTTGATGCAGAAGAAGAAGGCTCTAATCAAAATACATGA', 'ptg000001l.1005': 'ATGGCTGAGGACGGTATTGGTTTGCCAGCGGCTTCAGAAAAAAATAAG...AACAGTTATCTCCCTCCAAGAAAAAAGGCATCCTTCCGTGAACACTTGA', 'ptg000001l.1006': 'ATGGTGGCAACCATTGCTGTGTCTTGTTCGGAATTCATAAATTTTCAA...AGTTTCGGTTGGAGCCGTGAAAAAGACGGTCTCAAGCAAGAAACGGTAG', 'ptg000001l.1007': 'ATGTGGAATTTTGCATCTAATTGCATAGCTGGAAATATTGGATCAAAA...TTTTGCATATCCTAGTTTGGATTGGCTTGTCCGAGAAATCGTCCCTTAG', 'ptg000001l.1008': 'ATGTTTCCTATTTTACTCTTCCTCCTCACAGTTACTATTTCCACCACC...AAGGCTGCAAGTTGGGGCCTCGGATGATGAAAGTTCATCTTCATCCTAG', ...}, tmp='/var/lib/condor/execute/slot1/dir_38140/ks_tmp.3c8e141cb9cee6', codeml=<wgd.codeml.Codeml object>, preserve=False, times=1, min_length=100, method='fasttree', aligner='mafft', output_dir='/var/lib/condor/execute/slot1/dir_38140/wgd_ksd')
    302                 results_dict, msa=msa_path_protein, method="alc")
    303     else:
    304         clustering, pairwise_distances, tree_path = _weighting(
    305                 results_dict, msa=msa_path_protein, method=method)
    306     if clustering is not None:
--> 307         out = _calculate_weighted_ks(
        out = undefined
        clustering = array([[2.00000000e+01, 1.80000000e+01, 5.845136...1.23000000e+02, 1.64341494e+00, 6.30000000e+01]])
        results_dict = {'Ka':                 ptg000001l.2310 ptg000001l.2311 ...    0.0698            0.0

[63 rows x 63 columns], 'Ks':                 ptg000001l.2310 ptg000001l.2311 ...    0.7065            0.0

[63 rows x 63 columns], 'Omega':                 ptg000001l.2310 ptg000001l.2311 ...    0.0988            0.0

[63 rows x 63 columns]}
        pairwise_distances = {0: {0: 0.0, 1: 0.158656603, 2: 0.19943205, 3: 0.22707782199999998, 4: 1.17499233, 5: 1.3474487700000002, 6: 1.342737019, 7: 0.370011188, 8: 1.2996123169999998, 9: 0.39746069300000003, ...}, 1: {0: 0.158656603, 1: 0.0, 2: 0.144857715, 3: 0.172503487, 4: 1.168688817, 5: 1.3411452570000002, 6: 1.336433506, 7: 0.363707675, 8: 1.2933088039999998, 9: 0.39115718000000005, ...}, 2: {0: 0.19943205, 1: 0.144857715, 2: 0.0, 3: 0.148519106, 4: 1.209464264, 5: 1.381920704, 6: 1.377208953, 7: 0.40448312200000003, 8: 1.334084251, 9: 0.431932627, ...}, 3: {0: 0.22707782199999998, 1: 0.172503487, 2: 0.148519106, 3: 0.0, 4: 1.237110036, 5: 1.4095664760000002, 6: 1.404854725, 7: 0.432128894, 8: 1.3617300229999998, 9: 0.459578399, ...}, 4: {0: 1.17499233, 1: 1.168688817, 2: 1.2094642640000002, 3: 1.2371100359999998, 4: 0.0, 5: 1.7149128360000003, 6: 1.7102010850000002, 7: 1.179148544, 8: 1.667076383, 9: 1.2065980490000001, ...}, 5: {0: 1.34744877, 1: 1.3411452570000002, 2: 1.3819207039999999, 3: 1.409566476, 4: 1.714912836, 5: 0.0, 6: 1.066055209, 7: 1.351604984, 8: 1.6259631669999999, 9: 1.3790544889999998, ...}, 6: {0: 1.342737019, 1: 1.3364335059999999, 2: 1.377208953, 3: 1.404854725, 4: 1.710201085, 5: 1.066055209, 6: 0.0, 7: 1.346893233, 8: 1.6212514159999998, 9: 1.374342738, ...}, 7: {0: 0.370011188, 1: 0.363707675, 2: 0.40448312200000003, 3: 0.432128894, 4: 1.179148544, 5: 1.3516049840000002, 6: 1.346893233, 7: 0.0, 8: 1.3037685309999998, 9: 0.266968891, ...}, 8: {0: 1.2996123170000002, 1: 1.2933088040000003, 2: 1.3340842510000002, 3: 1.3617300230000002, 4: 1.6670763830000002, 5: 1.6259631670000003, 6: 1.6212514160000002, 7: 1.3037685310000002, 8: 0.0, 9: 1.331218036, ...}, 9: {0: 0.3974606930000001, 1: 0.39115718, 2: 0.431932627, 3: 0.4595783990000001, 4: 1.2065980490000001, 5: 1.3790544890000003, 6: 1.3743427380000002, 7: 0.26696889100000004, 8: 1.3312180359999999, 9: 0.0, ...}, ...}
        family_id = 'GF_000007'
    308                 clustering, results_dict, pairwise_distances, family_id
    309         )
    310         out = add_alignment_stats_(out, stats)
    311         logging.debug(out)

...........................................................................
/var/lib/condor/execute/slot1/dir_38140/wgd-1.1.1/wgd/ks_distribution.py in _calculate_weighted_ks(clustering=array([[2.00000000e+01, 1.80000000e+01, 5.845136...1.23000000e+02, 1.64341494e+00, 6.30000000e+01]]), pairwise_estimates={'Ka':                 ptg000001l.2310 ptg000001l.2311 ...    0.0698            0.0

[63 rows x 63 columns], 'Ks':                 ptg000001l.2310 ptg000001l.2311 ...    0.7065            0.0

[63 rows x 63 columns], 'Omega':                 ptg000001l.2310 ptg000001l.2311 ...    0.0988            0.0

[63 rows x 63 columns]}, pairwise_distances={0: {0: 0.0, 1: 0.158656603, 2: 0.19943205, 3: 0.22707782199999998, 4: 1.17499233, 5: 1.3474487700000002, 6: 1.342737019, 7: 0.370011188, 8: 1.2996123169999998, 9: 0.39746069300000003, ...}, 1: {0: 0.158656603, 1: 0.0, 2: 0.144857715, 3: 0.172503487, 4: 1.168688817, 5: 1.3411452570000002, 6: 1.336433506, 7: 0.363707675, 8: 1.2933088039999998, 9: 0.39115718000000005, ...}, 2: {0: 0.19943205, 1: 0.144857715, 2: 0.0, 3: 0.148519106, 4: 1.209464264, 5: 1.381920704, 6: 1.377208953, 7: 0.40448312200000003, 8: 1.334084251, 9: 0.431932627, ...}, 3: {0: 0.22707782199999998, 1: 0.172503487, 2: 0.148519106, 3: 0.0, 4: 1.237110036, 5: 1.4095664760000002, 6: 1.404854725, 7: 0.432128894, 8: 1.3617300229999998, 9: 0.459578399, ...}, 4: {0: 1.17499233, 1: 1.168688817, 2: 1.2094642640000002, 3: 1.2371100359999998, 4: 0.0, 5: 1.7149128360000003, 6: 1.7102010850000002, 7: 1.179148544, 8: 1.667076383, 9: 1.2065980490000001, ...}, 5: {0: 1.34744877, 1: 1.3411452570000002, 2: 1.3819207039999999, 3: 1.409566476, 4: 1.714912836, 5: 0.0, 6: 1.066055209, 7: 1.351604984, 8: 1.6259631669999999, 9: 1.3790544889999998, ...}, 6: {0: 1.342737019, 1: 1.3364335059999999, 2: 1.377208953, 3: 1.404854725, 4: 1.710201085, 5: 1.066055209, 6: 0.0, 7: 1.346893233, 8: 1.6212514159999998, 9: 1.374342738, ...}, 7: {0: 0.370011188, 1: 0.363707675, 2: 0.40448312200000003, 3: 0.432128894, 4: 1.179148544, 5: 1.3516049840000002, 6: 1.346893233, 7: 0.0, 8: 1.3037685309999998, 9: 0.266968891, ...}, 8: {0: 1.2996123170000002, 1: 1.2933088040000003, 2: 1.3340842510000002, 3: 1.3617300230000002, 4: 1.6670763830000002, 5: 1.6259631670000003, 6: 1.6212514160000002, 7: 1.3037685310000002, 8: 0.0, 9: 1.331218036, ...}, 9: {0: 0.3974606930000001, 1: 0.39115718, 2: 0.431932627, 3: 0.4595783990000001, 4: 1.2065980490000001, 5: 1.3790544890000003, 6: 1.3743427380000002, 7: 0.26696889100000004, 8: 1.3312180359999999, 9: 0.0, ...}, ...}, family_id='GF_000007')
    192                     pairwise_estimates['Ka'].iloc[i, j],
    193                     pairwise_estimates['Omega'].iloc[i, j],
    194                     distance, grouping_node
    195                 ]
    196 
--> 197                 if pairwise_estimates['Ks'].iloc[i, j] > 5:
        pairwise_estimates.iloc = undefined
        i = 20
        j = 18
    198                     out.add(grouping_node)
    199 
    200     df = pd.DataFrame.from_dict(weights, orient='index')
    201     df.columns = ['Paralog1', 'Paralog2', 'Family',

TypeError: '>' not supported between instances of 'str' and 'int'
___________________________________________________________________________

**Comment by heche-psb** [comment]
Hi, a quick test to help debugging. Could you try to install `wgd v1` using `python 3.6.5` instead of `python 3.8` and try again?
