### ISSUE TITLE
viz running problem

### ISSUE THREAD

**Issue by majssssa** [heche-psb/wgd#21]
Hello, I encountered a very fast problem when using the viz module of wgd v2.0.25. According to the explanation on the official website, there will be a -fa option after v 2.2.24, but this option does not appear when I run wgd viz -h, and there will be an Error when I run it directly: no such option: -f

**Comment by majssssa** [comment]
Hello, I have solved the last problem. I installed v 2.0.24, and the -fa option appeared in the viz module. But when I run viz I get the following error message.Seems to be the numpy version of the problem, please tell me how to solve this.

AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code,  use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar  type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by heche-psb** [comment]
Hi, thanks for posing the issue! The version of `python` and `numpy` that I tested with is `python` 3.8.3 and `numpy` 1.19.0. Higher version of `numpy` might indeed induce the issue you met, the AttributeError. Could you please install this specific version and try again?
