### ISSUE TITLE
Error running wgd dmd with the globalmrbh flag

### ISSUE THREAD

**Issue by niWdooG** [heche-psb/wgd#27]
Hi, 

I have an issue running wgd v2.0.29 with the globalmrbh flag [wgd dmd --globalmrbh -I 2 -e 1e-10 -bs 100 -np 5 --to_stop --cds SalCuc.fa AzoFil.fa -n 40 -o wgd_globalmrbh -t tmp]:

> multiprocessing.pool.RemoteTraceback: 
> """
> Traceback (most recent call last):
>   File "/home/user1/mambaforge/envs/WGD/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 350, in __call__
>     return self.func(*args, **kwargs)
>   File "/home/user1/mambaforge/envs/WGD/lib/python3.8/site-packages/joblib/parallel.py", line 131, in __call__
>     return [func(*args, **kwargs) for func, args, kwargs in self.items]
>   File "/home/user1/mambaforge/envs/WGD/lib/python3.8/site-packages/joblib/parallel.py", line 131, in <listcomp>
>     return [func(*args, **kwargs) for func, args, kwargs in self.items]
>   File "/home/user1/mambaforge/envs/WGD/lib/python3.8/site-packages/wgd/core.py", line 822, in get_mrbh
>     s_i.get_rbh_orthologs(s_j, cscore, False, eval=eval)
>   File "/home/user1/mambaforge/envs/WGD/lib/python3.8/site-packages/wgd/core.py", line 391, in get_rbh_orthologs
>     df = self.run_diamond(seqs, orthoinfer, eval=eval)
>   File "/home/user1/mambaforge/envs/WGD/lib/python3.8/site-packages/wgd/core.py", line 384, in run_diamond
>     df = normalizebitscore(self.gene_length,df,outpath,sgidmaps=sgidmaps,idmap=self.idmap,seqmap=seqs.idmap,bins = self.bins,hitper = self.np).drop(columns=[11,12]).rename(columns={13:11})
>   File "/home/user1/mambaforge/envs/WGD/lib/python3.8/site-packages/wgd/core.py", line 169, in normalizebitscore
>     df.loc[:,15] = df[1].apply(lambda x:combinedidmaps[x])
>   File "/home/user1/mambaforge/envs/WGD/lib/python3.8/site-packages/pandas/core/series.py", line 4433, in apply
>     return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
>   File "/home/user1/mambaforge/envs/WGD/lib/python3.8/site-packages/pandas/core/apply.py", line 1088, in apply
>     return self.apply_standard()
>   File "/home/user1/mambaforge/envs/WGD/lib/python3.8/site-packages/pandas/core/apply.py", line 1143, in apply_standard
>     mapped = lib.map_infer(
>   File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
>   File "/home/user1/mambaforge/envs/WGD/lib/python3.8/site-packages/wgd/core.py", line 169, in <lambda>
>     df.loc[:,15] = df[1].apply(lambda x:combinedidmaps[x])
> KeyError: 'SalCuc.fa_04013'

Attachments:
1. [log.txt](https://github.com/heche-psb/wgd/files/14833671/log.txt)
2. The dataset used [Data_CDS.zip](https://github.com/heche-psb/wgd/files/14833679/Data_CDS.zip)

Best,
Evgenii

**Comment by heche-psb** [comment]
Hi, I did reproduce your error. It's because the two cds files, `AzoFil.fa` and `SalCuc.fa` have same gene names, which causes a invalid dictionary with less gene names as keys than it is expected to have. The issue can be quickly solved by changing the gene names of either file, for instance, `sed -i "s/>/>Sal_/g" SalCuc.fa`. But you raise a good caution of the stability of handling gene names for condition like this. I will improve the code this week for this issue. Thanks!

**Comment by heche-psb** [comment]
You should have log like this if you changed the gene names as suggested above:
```
(ENV_wgd) $ wgd dmd -gm AzoFil.fa SalCuc.fa --cds --to_stop -o strict_cds
11:40:17 INFO     This is wgd v2.0.29                                                                       cli.py:32
11:40:20 WARNING  Translation error (First codon 'AAA' is not a start codon) in seq g12020.t1             core.py:309
11:40:23 WARNING  Translation error (Final codon 'GCA' is not a stop codon) in seq g528.t1                core.py:309
11:40:24 WARNING  Translation error (First codon 'AAT' is not a start codon) in seq g26044.t1             core.py:309
         ...
         WARNING  Translation error (Sequence length 359 is not a multiple of three) in seq Sal_g12667.t1 core.py:309
         WARNING  Translation error (Sequence length 1042 is not a multiple of three) in seq              core.py:309
                  Sal_g16589.t1
         INFO     tmpdir = wgdtmp_37a6c3b1-602d-48e4-885a-ee4635b97fd7 for AzoFil.fa                       cli.py:120
         INFO     tmpdir = wgdtmp_cca8a405-0b13-4977-8dc6-5d6f5a3a4559 for SalCuc.fa                       cli.py:120
         INFO     Multiple cds files: will compute globalMRBH orthologs or cscore-defined homologs        core.py:843
                  regardless of focus species
11:45:22 INFO     AzoFil.fa vs. SalCuc.fa                                                                 core.py:821
11:45:53 INFO     Normalization between AzoFil.fa & SalCuc.fa                                             core.py:382
         INFO     100 bins & upper 5% hits in linear regression                                           core.py:383
11:46:37 INFO     Total run time: 378s                                                                   core.py:1619
         INFO     Done                                                                                   core.py:1620
```

**Comment by niWdooG** [comment]
Thank you for the quick response!

The issue is solved.

Best,
Evgenii
