### ISSUE TITLE
Unable to install wgd

### ISSUE THREAD

**Issue by karthickbrlab** [heche-psb/wgd#32]
hi

I have tried installing wgd from source.

But failed due to numpy error. IM unable to install older verwsion of numpy==1.19.0.

Is there any other way to install with latest version of numpy?

**Comment by heche-psb** [comment]
Hi, it's better to creat a separate virtual environment for `wgd v2` (well, for any other python packages that have some dependency on external softwares I would suggest the same). You may first install `numpy==1.19.0`, and then install `wgd v2`.

**Comment by karthickbrlab** [comment]
Yes i have tried this..
But i couldn't
can i install any nearby version of numpy? 1.19.2 or 1.19.5

**Comment by heche-psb** [comment]
Yes, you may try it. Please let me know if it works so we can help other users as well!
