### ISSUE TITLE
peak

### ISSUE THREAD

**Issue by ilaydagulmez** [heche-psb/wgd#37]
Hi, it's me again 🥹 

`wgd syn ` completed thanks to you. Now I try the` wgd peak ` with this command:

wgd peak 20628_8.cds.fasta.tsv.ks.tsv -ap wgd_syn/iadhore-out/anchorpoints.txt -sm wgd_syn/iadhore-out/segments.txt -le wgd_syn/iadhore-out/list_elements.txt -mp wgd_syn/iadhore-out/multiplicon_pairs.txt

I got this error:

<img width="2560" alt="Screenshot 2024-06-03 at 16 14 54" src="https://github.com/heche-psb/wgd/assets/163100594/83d7ee46-0ab8-48ba-9e17-618e39cfd1e0">

I searched about this error but I couldn't find anything. Sorry about writing all the time... 

Thanks.

**Comment by heche-psb** [comment]
Hi, could you `cat wgd_syn/iadhore-out/anchorpoints.txt` and show me the content? Your log showed that there were less than 2 available datapoints in analysis.

**Comment by ilaydagulmez** [comment]
Hi, sorry for my late response. Here is the` anchorpoints.txt `

<img width="565" alt="Ekran Resmi 2024-06-04 09 02 05" src="https://github.com/heche-psb/wgd/assets/163100594/b1d961cf-5286-4bd3-a5d5-a2dc4aaecc87">

**Comment by heche-psb** [comment]
Hi, have you tried `wgd syn` with your Ks data? I wonder how the anchor Ks distribution looks like.

**Comment by ilaydagulmez** [comment]
Yes, even you added the `--pathiadhore` parameter for my errors.

**Comment by heche-psb** [comment]
I think it's simply that your genome has sparse collinearity.

**Comment by ilaydagulmez** [comment]
Okay, I think I can't use` wgd peak ` with `syn` outputs cause of my genome data.

**Comment by heche-psb** [comment]
Is scarce collinearity something you would expect? If so, it just means that your species lacks recent WGD.

**Comment by ilaydagulmez** [comment]
I'm going to research and try again the `wgd peak` analysis. If there is still a problem, I will reopen the issue. Thanks for your help.

**Comment by ilaydagulmez** [comment]
`wgd ksd ` results don't show the value, is this caused of an error? I mean, I gave the `ksd.tsv ` to `syn ` literally and maybe it can affect the other steps. However when I tried the `--pairwise` parameter, the job was killed cause of 3 days limit. 

<img width="2560" alt="Screenshot 2024-06-04 at 10 02 27" src="https://github.com/heche-psb/wgd/assets/163100594/acf10453-38c2-44c7-9242-698b62dcc7c9">

Another suggest, can I `BLAST` my cds file before the using` wgd v2`

**Comment by heche-psb** [comment]
I think I have already explained why there are Ks values as NaN.

**Comment by ilaydagulmez** [comment]
Yes, but the main question is whether the NaN values do effect the `wgd syn` results.

**Comment by heche-psb** [comment]
Hi, extra Ks data will lead to extra anchor Ks distribution and Ks dotplot while the original collinear results remain untouched.

**Comment by ilaydagulmez** [comment]
Thanks for your help!

**Comment by ilaydagulmez** [comment]
Hi again, I have checked my error (https://github.com/heche-psb/wgd/issues/37#issue-2331136165) and folders and I realized that my 'syn' analysis is completed, but there are no .png and .svg files, only 'i-adhore' and .tsv and .csv files. Any suggestions? Many thanks.

**Comment by heche-psb** [comment]
If there was no error log from `wgd syn`, I think it's because the genome has too few anchor pairs detected.

**Comment by ilaydagulmez** [comment]
Thanks for your assistance. I will attempt to filter the gene predictions. I believe there may be an issue with the number of genes I have. Thank you.

**Comment by ilaydagulmez** [comment]
Hi, even when I try with filtered cds file I get the same error:

<img width="2560" alt="Screenshot 2024-06-26 at 08 32 46" src="https://github.com/heche-psb/wgd/assets/163100594/d2601dac-e009-4056-8166-67b09c604532">

The `syn` file looks like this:
<img width="1866" alt="Screenshot 2024-06-26 at 08 34 03" src="https://github.com/heche-psb/wgd/assets/163100594/190b28ca-f233-45fb-bebf-2333e5fdeed7">

I'm unsure why I can't run "peak" with "syn" files. I don't think it is caused of my genome.

**Comment by ilaydagulmez** [comment]
Hi, any suggestions? I couldn't obtain the WGD date, which is the main result file I want to get, cause of stuck in the 'syn' step.
Best 

İlayda

**Comment by heche-psb** [comment]
Hi, as you have shown here https://github.com/heche-psb/wgd/issues/37#issuecomment-2146677683, too few anchor pairs were detected by `i-adhore` and I guess that's why `wgd peak` crashed. Could you please show the content of your current "anchorpoints.txt" file?

**Comment by ilaydagulmez** [comment]
Hi, here is the "anchorpoints.txt" file:

<img width="686" alt="Ekran Resmi 2024-07-05 11 49 36" src="https://github.com/heche-psb/wgd/assets/163100594/a00d9d44-2884-4c19-a8d1-9a5cf43df6c5">

Best

**Comment by heche-psb** [comment]
`wgd peak` was mainly designed to find peaks for anchor Ks distribution, which would not give meaningful results to such few anchor genes I think. What is your purpose of running `wgd peak` upon several anchor genes?

**Comment by ilaydagulmez** [comment]
Our purpose is estimate the WGD date like pipeline 6. I understand that our example has not applicable for this.

**Comment by heche-psb** [comment]
If you could use some other methods and identify some potential gene duplicates that is believed to be from WGD, you can simply prepare a tab-separated file with two columns "gene_x" and "gene_y" to feed `wgd peak`, which can also fulfill your need, since what `wgd peak` does is to find crediable collinear gene duplicates for dating.

**Comment by ilaydagulmez** [comment]
Okey many thanks!
