### ISSUE TITLE
Number of threads not being passed

### ISSUE THREAD

**Issue by dfmoralesb** [heche-psb/wgd#46]
Hello. 

I'm using the flag `-n` or `--nthreads`, but I always get the below message, and wgd always uses 8 threads. Is there anything else that needs to be used? 

Thanks!

INFO     Note: detected 128 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.                                                                                            utils.py:144
INFO     Note: NumExpr detected 128 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.                                                                                                               utils.py:147
INFO     NumExpr defaulting to 8 threads.

**Comment by heche-psb** [comment]
Hi, `NumExpr` is mainly to speed up numerical expressions that involve large arrays. You should normally leave it as it is. The `-n` option is the real parameter that determines how many jobs can run in parallel.
