### ISSUE TITLE
TypeError: '>' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by dongyiyi** [heche-psb/wgd#50]
Hi,

Under LINUX, wgd v1.2
An error came up when I ran :
wgd  ksd --n_threads 8  -o A_vs_B.ksd  A_vs_B.dmd/A.cds_B.cds.rbh  A.cds  B.cds

/......./python3.9/site-packages/wgd/ks_distribution.py", line 197, in _calculate_weighted_ks
    if pairwise_estimates['Ks'].iloc[i, j] > 5:
TypeError: '>' not supported between instances of 'str' and 'int'

Specifically in this line:

if pairwise_estimates['Ks'].iloc[i, j] > 5:

Thanks!

**Comment by heche-psb** [comment]
Hi, the error means that there was no Ks data for that gene pair. I suggest that you use `wgd v2` for your analysis now, since the gene families constructed by `wgd v2` have the gene length bias corrected.
